*SHGetFolder

#Define CSIDL_APPDATA 0x001a
#Define CSIDL_COMMON_APPDATA 0x0023
#Define CSIDL_MYDOCUMENTS 0x000c
#Define CSIDL_MYPICTURES 0x0027
#Define SHGFP_TYPE_CURRENT 0
#Define SHGFP_TYPE_DEFAULT 1

* WinInet
#Define INTERNET_CONNECTION_MODEM 0x1
#Define INTERNET_CONNECTION_LAN   0x2
#Define INTERNET_CONNECTION_PROXY 0x4
